### ISSUE TITLE
Shows no xp being gained.

### ISSUE THREAD

**Issue by Remotag** [hybridbrizz/Xp-Goals#10]
Shows [ 0 / 500,000 ] with any of the skills/total xp options even though xp is being gained

**Comment by hybridbrizz** [comment]
Hello,

Thanks for reporting this. For now restarting Runelite should fix the issue. In general what's going on most likely has to do with switching profiles either manually or when Runelite updates. I'm working on a fix for supporting multiple profiles and expect this issue to get resolved with that update.

**Comment by Remotag** [comment]
Even after restarting the client before and after this recent update the issue persists unfortunately. And not sure if its helpful but I do only use one profile and never switch. Thanks

**Comment by hybridbrizz** [comment]
The update I just submitted should fix the issues your encountering. It takes a few days then it will be automatically updated. Thanks again for reporting this.

**Comment by hybridbrizz** [comment]
Should be fixed now. Please let me know if you run into any similar issues.
